### ISSUE TITLE
Additional Languages

### ISSUE THREAD

**Issue by rlavoie** [personality-insights/text-summary#1]
In order to add other languages would we just have to add another js file that we manually translate in the 118n folder and recompile? We are looking for English, Chinese, Portuguese, Spanish, French, Korean, Hindi, Arabic and Thai.

**Comment by arypbatista** [comment]
Yes, it is as you say @rlavoie, need help?

**Comment by germanattanasio** [comment]
Seems like the question was answer so I'm closing this
