### ISSUE TITLE
Error when using this package with Ionic 2

### ISSUE THREAD

**Issue by getflixFaisal** [personality-insights/text-summary#11]
Hello,

I tried to using this package & personality trait info for my android project using Ionic 2.
When I tried to build using --prod parameter, it gave me so many errors. But it's good when it tried to build using this command `ionic build android`.

Here is the error: [https://pastebin.com/3bDabnKB](https://pastebin.com/3bDabnKB)

I think most of the error caused by the browserify. Thank you

**Comment by soumak77** [comment]
This should be resolved with https://github.com/personality-insights/text-summary/pull/10
